app/models.py
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from . import login_manager
from datetime import datetime
from . import db

@login_manager.user_loader
def load_coach(user_id):
    return User.query.get(int(user_id))


class User(UserMixin,db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(255), index=True)
    email = db.Column(db.String(255), unique=True, index=True)
    bio = db.Column(db.String(255))
    profile_pic_pah = db.Column(db.String())
    joined = db.Column(db.DateTime, default=datetime.utcnow)
    pass_secure = db.Column(db.String(255))
    profile = db.relationship("Profile", backref="user", lazy="dynamic")

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.pass_secure, password)

    def __repr__(self):
        return f'User {self.username}'


class Profile(db.Model):
    __tablename__ = 'profiles'

    id = db.Column(db.Integer, primary_key=True)
    teamname = db.Column(db.String)
    vision = db.Column(db.String(255))
    mission = db.Column(db.String())
    # category = db.Column(db.String(255))
    members = db.Column(db.String)
    # Foreign key from users table to link teams and profiles
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))

    def save_profile(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_profiles(cls, id):
        profiles = Profile.query.filter_by(id=id).all()
        return profiles

    @classmethod
    def get_all_profiles(cls):
        profiles = Profile.query.order_by('-id').all()
        return profiles

    def __repr__(self):
        return f'Profile {self.teamname}'

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField,SelectField
from wtforms.validators import Required, Email, EqualTo


class ProfileForm(FlaskForm):
    teamname = StringField('Team Name',validators=[Required()])
    vision = StringField('Team Vision',validators = [Required()])
    mission = TextAreaField('Team Mission',validators = [Required()])
    members = TextAreaField('Add Team Members',validators = [Required()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy


# Initiating login manager
login_manager=LoginManager()


# Initialaizing Flask extensions
bootstrap = Bootstrap()
db = SQLAlchemy()

def create_app(config_name):
    app = Flask(__name__)

# Creating app configurations
    app.config.from_object(config_options[config_name])
    # config_options[config_name].init_app(app)


    # Initializing bootstrap
    bootstrap.init_app(app)

    # Initializing sqlalchemy database
    db.init_app(app)
    login_manager.init_app(app)
    # Registering blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    # Registering the authentication blueprint
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')

    # Initializing the login manager
    # login_manager.init_app(app)


    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import  forms,views

app/main/views.py
from flask import render_template, request, redirect, url_for, abort, flash
from . import main
from flask_login import login_required, current_user
from .. import db
from ..models import Profile,User
from app import login_manager
from .forms import ProfileForm

@main.route('/')
def index():
    '''
    View page function that creates and returns the post titles on the index page
    '''

    form = ProfileForm()

    # if form.validate_on_submit():
    #     new_team = Team(actual_post=form.post.data, user_id=current_user.id)
    #     # new_team.save_post()
    #     # flash('Team has been created successfully')
    #     return redirect(url_for('.index'))
    # # team = Team.query.all()
    title= 'moringa'
    return render_template('index.html',title = title)





@main.route('/profile/add',methods = ['GET','POST'])
@login_required
def new_profile():
    '''
    View pitch function that returns the pitch page and data
    '''
    form = ProfileForm()


    if form.validate_on_submit():
        teamname = form.teamname.data
        vision = form.vision.data
        mission = form.mission.data
        members = form.members.data

        new_profile = Profile(teamname=teamname,vision=vision,mision=mission,members=members,user_id=current_user.id)
        new_profile.save_profile()
        flash('Profile has been created!', 'success')
        return redirect(url_for('main.home'))

    return render_template('profile/profile.html', profile_form = form)

@main.route('/user')
def profile():
    # usr = User.query.filter_by(username = uname).first()
    user= current_user

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)
@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form)

app/templates/base.html
{% extends 'bootstrap/base.html' %}

<!-- Navbar block  -->
{% block styles %}
    {{super()}}
    <link rel="stylesheet" href="{{url_for('static',filename='css/post.css')}}">
{% endblock %}
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">

{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}
<!--Styles block-->

<!-- Content block -->

{% block content %}

<!-- Blog Category -->
<h3> Welcome to Coachya </h3>
<h4>List of Teams</h4>
<p>For Coaches, please choose any of the teams below to support</p>



{% endblock%}

app/templates/navbar.html
<div class="navbar navbar-inverse" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/"> My Blog </a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/">Home</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                <li><a href="/user">My Profile</a></li>
                <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
                {% else %}
                <li><a href="{{url_for('auth.login')}}">Sign in or Sign Up</a></li>
                {%endif%}
              </ul>
        </div>

    </div>
</div>

app/templates/profile/profile.html
{% block content %}
<div class="container">
    <div class="row">
        <!-- displaying  Username-->
    <div class="col-md-4">
        <h3> {{user.username| capitalize}} </h3>

    <!--Displaying user bio-->
    {% if user.bio %}
      <p> {{user.bio}}</p>
    {%else%}
      <p> {{user.username| capitalize}} has no bio </p>
    {% endif %}
    </div>

    <!--Display profile photo-->
    <div class="col-md-4">
    {% if user.profile_pic_path %}

    <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">

    {%else%}
    <p>No profile picture</p>

    {% endif %}

        {% if user == current_user %}
    <form  action="{{url_for('main.update_profile',uname=user.username)}}" method="post" enctype = "multipart/form-data">

      <input type="file"  name="photo" class="form-control" required>
      <input type="submit">
    </form>
      {% endif %}
        </div>
    </div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}